# TODO: Este é um exemplo, criar documentação da api
openapi: 3.0.3
info:
  title: Autenticacao API
  description: |-
    Api simples de autenticação
  version: 2.0.1
servers:
  - url: http://localhost:3000
tags:
  - name: user
    description: Operations about user
paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: Rota de cadastro de usuário
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user/login:
    post:
      tags:
        - user
      summary: Login
      description: Rota de login
      operationId: loginUser
      requestBody:
        description: Body de login
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccess'
        '400':
          description: Invalid username/password supplied
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        password:
          type: string
          example: '12345'
      xml:
        name: user
        
    LoginSuccess:
      type: object
      properties:
        message:
          type: string
          example: Usuário logado com sucesso